# robotpkg motion generation software
#

COMMENT=	Motion generation software

SUBDIR+=	dynamic-graph
SUBDIR+=	dynamic-graph-corba
SUBDIR+=	contlaw
SUBDIR+=	locoDemo-genom
SUBDIR+=	nhfc-genom3
SUBDIR+=	orocos-kdl
SUBDIR+=	pilo-genom
SUBDIR+=	py-dynamic-graph
SUBDIR+=	py-orocos-kdl
SUBDIR+=	py-sot-tools
SUBDIR+=	ros-orocos-kdl
SUBDIR+=	softMotion-libs
SUBDIR+=	sot-core
SUBDIR+=	sot-dynamic
SUBDIR+=	sot-pattern-generator

include ../mk/robotpkg.subdir.mk
