# robotpkg motion generation software
#

COMMENT=	Motion generation software

SUBDIR+=	contlaw
SUBDIR+=	locoDemo-genom
SUBDIR+=	pilo-genom
SUBDIR+=	stackoftasks
SUBDIR+=	softMotion-libs

include ../mk/robotpkg.subdir.mk
