# $NetBSD$
#

DISTNAME=		eltclsh-1.8
CATEGORIES=		shell
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		https://softs.laas.fr/openrobots/wiki/eltclsh
COMMENT=		Interactive shell for the TCL programming language.

GNU_CONFIGURE=		yes

include ../../devel/libedit/depend.mk
include ../../mk/robotpkg.mk
