# $NetBSD: Makefile,v 1.21 2006/08/22 23:27:23 joerg Exp $
#

DISTNAME=	libt3d-2.0

CATEGORIES=	math
MASTER_SITES=	${MASTER_SITES_OPENROBOTS}

MAINTAINER=	openrobots@laas.fr
#HOMEPAGE=	
COMMENT=	3d transformations, matrices and vector package.

GNU_CONFIGURE=	yes

include ../../mk/robotpkg.mk
