# robotpkg Makefile for:	graphics/ros-interactive-markers
# Created:			Charles Lesire on Tue, 8 Apr 2014
#

ROS_PKG=	interactive_markers
ROS_VERSION=	1.11.0
ROS_REPO=	ros-visualization

CATEGORIES=	graphics
ROS_COMMENT=	interactive marker library for RViz and similar visualizers

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../lang/ros-message-runtime/depend.mk
include ../../math/ros-geometry/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../mk/robotpkg.mk
