# robotpkg depend.mk for:	sysutils/ros-rviz
# Created:			Charles Lesire on Wed, 9 Apr 2014
#

ROS_PKG=	rviz
ROS_VERSION=	1.11.10
ROS_REPO=	ros-visualization

CATEGORIES=	sysutils
ROS_COMMENT=	3D visualization tool

include ../../meta-pkgs/ros-base/Makefile.common

DEPEND_ABI.libogre += libogre>=1.7

include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-cmake-modules/depend.mk
include ../../devel/ros-pluginlib/depend.mk
include ../../devel/ros-ros/depend.mk
include ../../devel/tinyxml/depend.mk
include ../../devel/yaml-cpp/depend.mk
include ../../graphics/assimp/depend.mk
include ../../graphics/ros-interactive-markers/depend.mk
include ../../graphics/ros-python-qt-binding/depend.mk
include ../../graphics/ros-robot-model/depend.mk
include ../../image/ros-image-common/depend.mk
include ../../image/ros-vision-opencv/depend.mk
include ../../interfaces/ros-comm-msgs/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../interfaces/ros-map-msgs/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../mapping/ros-laser-geometry/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/ros-geometry/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../net/ros-resource-retriever/depend.mk
include ../../mk/sysdep/libogre.mk
include ../../mk/sysdep/qt4-libs.mk
include ../../mk/sysdep/qt4-opengl.mk
include ../../mk/robotpkg.mk
