# robotpkg Makefile for:	supervision/ros-executive-smach
# Created:			Séverin Lemaignan on Tue, 06 Aug 2013
#

ROS_PKG=	executive_smach
ROS_VERSION=	2.5.2
ROS_METAPKG=	yes

CATEGORIES=	supervision
ROS_COMMENT=	procedural python-based task execution framework

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../lang/ros-message-runtime/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../mk/robotpkg.mk
