# robotpkg graphics tools
#

COMMENT=	Graphics tools

SUBDIR+=	gdhe
SUBDIR+=	kpp-interface
SUBDIR+=	kpp-interfacewalk
SUBDIR+=	kpp-interfacedisplay
SUBDIR+=	laaswm
SUBDIR+=	laaswm-libs
SUBDIR+=	vrml97
SUBDIR+=	wxGTK

include ../mk/robotpkg.subdir.mk
