# robotpkg computer graphics tools
#

COMMENT=	Computer graphics tools

SUBDIR+=	blender
SUBDIR+=	coldman-genom
SUBDIR+=	coldman-libs
SUBDIR+=	collada-dom
SUBDIR+=	gdhe
SUBDIR+=	grh2
SUBDIR+=	kpp-interface
SUBDIR+=	kpp-interfacewalk
SUBDIR+=	kpp-interfacedisplay
SUBDIR+=	laaswm
SUBDIR+=	laaswm-libs
SUBDIR+=	openvrml-libs
SUBDIR+=	pqp
SUBDIR+=	primitiveShapes-libs
SUBDIR+=	Togl
SUBDIR+=	vcglib
SUBDIR+=	vrml97
SUBDIR+=	wxGTK

include ../mk/robotpkg.subdir.mk
