# robotpkg Makefile for:	simulation/py-hpp-environments
# Created:			Guilhem Saurel on Tue, 14 Apr 2020
#

HPP_PACKAGE=		hpp-environments
HPP_COMMENT=		Environments and robot descriptions for HPP
HPP_VERSION=		4.10.1

CATEGORIES=		simulation

USE_PYTHON_ONLY=	yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../simulation/hpp-environments/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++11.mk
include ../../mk/robotpkg.mk
