# robotpkg Makefile for:	hardware/ros-driver-common
# Created:			Séverin Lemaignan on Tue, 06 Aug 2013
#

ROS_PKG=		driver_common
ROS_VERSION=	1.6.6
ROS_REPO=		ros-drivers
ROS_METAPKG=	yes

CATEGORIES=	hardware
ROS_COMMENT=	deprecated common resources for drivers in ROS

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../lang/ros-message-runtime/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../mk/robotpkg.mk
