# robotpkg Makefile for:	graphics/ros-urdf
# Created:			Anthony Mallet on Tue, 11 Sep 2018
#

ROS_PKG=	urdf
ROS_METAPKG=	yes
ROS_VERSION=	1.13.2

CATEGORIES=	graphics
ROS_COMMENT=	C++ parser for the Unified Robot Description Format (URDF)

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-cmake-modules/depend.mk
include ../../devel/ros-pluginlib/depend.mk
include ../../devel/tinyxml/depend.mk
include ../../graphics/urdfdom/depend.mk
include ../../graphics/urdfdom-headers/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../sysutils/ros-console-bridge/depend.mk
include ../../mk/sysdep/tinyxml2.mk
include ../../mk/robotpkg.mk
