# robotpkg path planning algorithms
#

COMMENT=	Path planning algorithms and tools

SUBDIR+=	aspect-genom
SUBDIR+=	dtm-genom
SUBDIR+=	gik-genom
SUBDIR+=	hpp-core
SUBDIR+=	hpp-gik
SUBDIR+=	hpp-openhrp
SUBDIR+=	hpp-walkfootplanner
SUBDIR+=	hpp-walkplanner
SUBDIR+=	jrl-walkgen
SUBDIR+=	kineo-pp
SUBDIR+=	libdtm
SUBDIR+=	libp3d
SUBDIR+=	ndd-genom
SUBDIR+=	p3d-genom
SUBDIR+=	walk-genom

include ../mk/robotpkg.subdir.mk
