# robotpkg path planning algorithms
#

COMMENT=	Path planning algorithms and tools

SUBDIR+=	hpp-core
SUBDIR+=	hpp-gik
SUBDIR+=	hpp-openhrp
SUBDIR+=	hpp-walkplanner
SUBDIR+=	jrl-walkgen
SUBDIR+=	kineo-pp

include ../mk/robotpkg.subdir.mk
