# robotpkg path planning algorithms
#
# Please list in alphabetical order
#

COMMENT=	Path planning algorithms and tools

SUBDIR+=	aspect-genom
SUBDIR+=	hpp-constrained
SUBDIR+=	hpp-constrained-corba
SUBDIR+=	hpp-constrained-planner
SUBDIR+=	hpp-corbaserver
SUBDIR+=	hpp-core
SUBDIR+=	hpp-dynamic-obstacle
SUBDIR+=	hpp-gik
SUBDIR+=	hpp-hik
SUBDIR+=	hpp-kwsio
SUBDIR+=	hpp-kwsplus
SUBDIR+=	hpp-localstepper
SUBDIR+=	hpp-model
SUBDIR+=	hpp-model-urdf
SUBDIR+=	hpp-openhrp
SUBDIR+=	hpp-roboptim
SUBDIR+=	hpp-util
SUBDIR+=	hpp-walkfootplanner
SUBDIR+=	hpp-walkplanner
SUBDIR+=	hpp-wholebody-step-corba
SUBDIR+=	hpp-wholebody-step-planner
SUBDIR+=	hpp-worldmodelplanner
SUBDIR+=	jrl-walkgen
SUBDIR+=	libp3d
SUBDIR+=	ndd-genom
SUBDIR+=	p3d-genom

include ../mk/robotpkg.subdir.mk
