# robotpkg Makefile for:	meta-pkgs/jafar
# Created:			Anthony Mallet on Mon, 10 Dec 2012
#

DISTNAME=	jafar-20121210
CATEGORIES=	meta-pkgs

MAINTAINER=	jafar@laas.fr
HOMEPAGE=	http://www.openrobots.org/wiki/jafar/
COMMENT=	Jafar is A Framework for Algorithms development in Robotics

META_PACKAGE=	yes
NOT_FOR_PLATFORM=

include ../../devel/jafar-kernel/depend.mk
include ../../mk/robotpkg.mk
