#
# Copyright (c) 2007,2010 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      Anthony Mallet on Sun Jan 28 2007
#

DISTNAME=		mkdep-2.7
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		https://softs.laas.fr/openrobots/wiki/mkdep
COMMENT=		Automated make(1) dependency generation

LICENSE=		2-clause-bsd

NOT_FOR_PLATFORM=	# empty
GNU_CONFIGURE=		yes

include ../../mk/robotpkg.mk
