# Copyright (c) 2008 LAAS/CNRS
# All rights reserved.
#
DISTNAME=		libpom-1.1
CATEGORIES=		localization
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Global robot position management library.

GNU_CONFIGURE=		yes
USE_PKG_CONFIG=		yes

include ../../math/t3d/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
