# $NetBSD$
#

DISTNAME=		libpom-1.1
CATEGORIES=		localization
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Global robot position management library.

GNU_CONFIGURE=		yes
USE_PKG_CONFIG=		yes

DEPENDS+=		libt3d>=2.3:../../math/t3d

include ../../mk/robotpkg.mk
