# robotpkg Makefile for:	devel/jafar-kernel
# Created:			Redouane Boumghar on Thu, 17 Mar 2011
#

JAFAR_PKG=		kernel-0.5

CATEGORIES=		devel
JAFAR_COMMENT=		common tools (exceptions, logging facility ...)

include ../../meta-pkgs/jafar/Makefile.common

include ../../mk/robotpkg.mk
