# robotpkg Makefile for:	net/ros-resource_retriever
# Created:			Anthony Mallet on Thu, 14 Aug 2014
#

ROS_PKG=	resource_retriever
ROS_VERSION=	1.12.4

CATEGORIES=	net
ROS_COMMENT=	API to retrieve data from url-format files

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-ros/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../mk/sysdep/libcurl.mk
include ../../mk/robotpkg.mk
