# $LAAS: Makefile 2008/06/17 16:49:06 mallet $
#
# Copyright (c) 2007-2008 LAAS/CNRS
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice  and this list of  conditions in the documentation   and/or
#      other materials provided with the distribution.
#
#                                     Florent Lamiraux on Wed Oct 10 2007
#

DISTNAME=	hrp2_14-1.4

CATEGORIES=	robots
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=hrp2_14/}

MAINTAINER=	gepetto@laas.fr
#HOMEPAGE=	
COMMENT=	Data and functions specific to HRP2-14.

GNU_CONFIGURE=	yes

include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
