# $LAAS: Makefile 2009/03/07 00:13:41 tho $
#
# Copyright (c) 2008-2009 LAAS/CNRS
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without   fee is hereby granted, provided   that the above  copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS  SOFTWARE INCLUDING ALL  IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR  BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR  ANY DAMAGES WHATSOEVER RESULTING  FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION,   ARISING OUT OF OR IN    CONNECTION WITH THE USE   OR
# PERFORMANCE OF THIS SOFTWARE.
#
#                                             Anthony Mallet on Mon Apr 14 2008
#

DISTNAME=		sphinx2-0.6
CATEGORIES=		audio
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=cmusphinx/}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://cmusphinx.sourceforge.net
COMMENT=		Carnegie Mellon University\'s speech recognition engine.

GNU_CONFIGURE=		yes

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
