# $Id:$
#

DISTNAME=		sphinx2-0.6
CATEGORIES=		audio
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=cmusphinx/}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://cmusphinx.sourceforge.net
COMMENT=		Carnegie Mellon University\'s speech recognition engine.

GNU_CONFIGURE=		yes

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
