# $NetBSD$
#

DISTNAME=		genom-2.0
PKGREVISION=		1
CATEGORIES=		architecture
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		https://softs.laas.fr/openrobots/wiki/genom
COMMENT=		Software components generator for robotics architecture.

GNU_CONFIGURE=		yes
USE_PKG_CONFIG=		yes

include ../../devel/pocolibs/depend.mk
include ../../mk/robotpkg.mk
