# $NetBSD: Makefile,v 1.21 2006/08/22 23:27:23 joerg Exp $
#

DISTNAME=	matrixabstractlayer-${VERSION}
PKGNAME=	jrl-mal-${VERSION}
VERSION=	1.4

CATEGORIES=	interfaces
MASTER_SITES=	${MASTER_SITE_JRL}

MAINTAINER=	openrobots@laas.fr
#HOMEPAGE=	
COMMENT=	matrix abstraction layer for boost or vnl.

GNU_CONFIGURE=	yes
USE_PKG_CONFIG=	yes

include options.mk
include ../../mk/robotpkg.mk
