# robotpkg Makefile for:	net/netshring
# Created:			Anthony Mallet on Wed, 14 Nov 2007
#

DISTNAME=		netshring-1.2
CATEGORIES=		net
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Networked FIFOs
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../pkgtools/pkg-config/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
