# robotpkg Makefile for:	robots/py39-hpp-universal-robot
# Created:			Guilhem Saurel on Tue, 13 Apr 2021
#

HPP_PACKAGE=			hpp-universal-robot
HPP_COMMENT=			Data specific to robots ur5 and ur10 for hpp-corbaserver

CATEGORIES=			robots
PYTHON_NOTAG_CONFLICT=		yes

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
