# robotpkg Makefile for:	robots/py27-example-robot-data
# Created:			Guilhem Saurel on Tue, 14 Apr 2020
#

ORG=			gepetto
NAME=			example-robot-data
VERSION=		3.6.0

CATEGORIES=		robots
COMMENT=		Robot URDFs for benchmarking and developed examples
LICENSE=		2-clause-bsd
MAINTAINER=		gepetto@laas.fr

USE_PYTHON_ONLY=	true

include ../../devel/jrl-cmakemodules/Makefile.common

include ../../graphics/urdfdom-headers/depend.mk
include ../../graphics/urdfdom/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/pinocchio/depend.mk
include ../../math/py-eigenpy/depend.mk
include ../../math/py-pinocchio/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../robots/example-robot-data/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
