# robotpkg meta-pkgs

COMMENT=	Collections of other packages

SUBDIR+=	boost
SUBDIR+=	dala
SUBDIR+=	gearbox
SUBDIR+=	hpp
SUBDIR+=	jafar
SUBDIR+=	mana
SUBDIR+=	ros-base

include ../mk/robotpkg.subdir.mk
