# robotpkg meta-pkgs

COMMENT=	Collections of other packages

SUBDIR+=	boost
SUBDIR+=	dala
SUBDIR+=	gearbox
SUBDIR+=	hpp
SUBDIR+=	jafar
SUBDIR+=	mana
SUBDIR+=	minnie
SUBDIR+= 	orocos-toolchain
SUBDIR+=	ros-base
SUBDIR+=	ros-desktop
SUBDIR+=	ros-robot

include ../mk/robotpkg.subdir.mk
