# robotpkg Makefile for:	lang/ros-message-generation
# Created:			Anthony Mallet on Sun, 23 Jun 2013
#

ROS_PKG=	message_generation
ROS_VERSION=	0.2.9

CATEGORIES=	lang
ROS_COMMENT=	build-time dependency for language bindings of messages

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../lang/ros-gencpp/depend.mk
include ../../lang/ros-genlisp/depend.mk
include ../../lang/ros-genpy/depend.mk
include ../../middleware/ros-genmsg/depend.mk
include ../../mk/robotpkg.mk
