# robotpkg architecture tools
#

COMMENT=	Robotics architecture tools

SUBDIR+=	ace
SUBDIR+=	genBasic-genom
SUBDIR+=	genHum-genom
SUBDIR+=	genPos-genom
SUBDIR+=	genom
SUBDIR+=	genom-openhrp-plugin
SUBDIR+=	netshring
SUBDIR+=	openhrp
SUBDIR+=	openprs
SUBDIR+=	openrtm-aist
SUBDIR+=	transgen
SUBDIR+=	yarp

include ../mk/robotpkg.subdir.mk
