# robotpkg architecture tools
#

COMMENT=	Robotics architecture tools

SUBDIR+=	genom
SUBDIR+=	orocos-ocl
SUBDIR+=	robotis-oroyarp
SUBDIR+=	transgen
SUBDIR+=	urbi
SUBDIR+=	yarp

include ../mk/robotpkg.subdir.mk
