# robotpkg architecture tools
#

COMMENT=	Robotics architecture tools

SUBDIR+=	genom
SUBDIR+=	genom3
SUBDIR+=	genom3-pocolibs
SUBDIR+=	genom3-ros
SUBDIR+=	orocos-ocl

include ../mk/robotpkg.subdir.mk
