# robotpkg Makefile for:	devel/ros-ros
# Created:			Anthony Mallet on Mon, 10 Dec 2012
#

ROS_PKG=	cmake_modules
ROS_VERSION=	0.3.1

CATEGORIES=	devel
ROS_COMMENT=	cmake modules commonly used by ROS packages
HOMEPAGE=	http://wiki.ros.org/cmake_modules

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../mk/robotpkg.mk
