# robotpkg Makefile for:	devel/ament-cmake-ros
# Created:			Anthony Mallet on Wed,  6 Apr 2022
#

ROS2_PKG=	ament_cmake_ros
ROS2_VERSION=	0.10.0
PKGNAME=	$(subst _,-,${DISTNAME})

CATEGORIES=	devel
ROS2_COMMENT=	specific CMake bits in the ament buildsystem.

include ../../meta-pkgs/ros2-core/Makefile.common

CONFIGURE_DIRS=	${ROS2_PKG}

include ../../mk/robotpkg.mk
