# robotpkg Makefile for:	devel/roscpp-core
# Created:			Anthony Mallet on Mon, 10 Dec 2012
#

ROS_PKG=	roscpp_core
ROS_METAPKG=	yes
ROS_VERSION=	0.3.15

CATEGORIES=	devel
ROS_COMMENT=	underlying data libraries for roscpp messages

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../devel/ros-catkin/depend.mk
include ../../mk/robotpkg.mk
