# robotpkg Makefile for:	devel/ros2-test-interface-files
# Created:			Anthony Mallet on Wed,  6 Apr 2022
#

ROS2_PKG=	test_interface_files
ROS2_VERSION=	0.9.1

CATEGORIES=	interfaces
ROS2_COMMENT=	message definitions used for testing purposes.

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../mk/robotpkg.mk
