# $LAAS: Makefile 2008/05/25 12:26:45 tho $
#
# Copyright (c) 2008 LAAS/CNRS
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice  and this list of  conditions in the documentation   and/or
#      other materials provided with the distribution.
#
#                                      Arnaud Degroote on Sat May 17 2008
#

DISTNAME=		genBasic-genom-0.1
CATEGORIES=		architecture
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Common simple data structures for GenoM modules

GNU_CONFIGURE=		yes

GENOM_MODULE=		genBasic
include ../../architecture/genom/depend.mk

include ../../mk/robotpkg.mk
