#
# Copyright (c) 2008,2010 LAAS/CNRS
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice  and this list of  conditions in the documentation   and/or
#      other materials provided with the distribution.
#
#                                       Arnaud Degroote on Wed Apr 22 2008
#

OROYARP_VERSION=		1.2
DISTNAME=		robotis-oroyarp-${OROYARP_VERSION}
CATEGORIES=		architecture
MASTER_SITES=	http://robotis.onera.fr/sites/robotis.onera.fr/files/
EXTRACT_SUFX=	.tar

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://robotis.onera.fr
COMMENT=		The Orocos / YARP binding 

USE_LANGUAGES=	c c++

include ../../architecture/orocos-ocl/depend.mk
include ../../architecture/orocos-rtt/depend.mk
include ../../architecture/yarp/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
