#
# Copyright (c) 2009 LAAS/CNRS
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without   fee is hereby granted, provided   that the above  copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS  SOFTWARE INCLUDING ALL  IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR  BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR  ANY DAMAGES WHATSOEVER RESULTING  FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION,   ARISING OUT OF OR IN    CONNECTION WITH THE USE   OR
# PERFORMANCE OF THIS SOFTWARE.
#
#                                             Anthony Mallet on Thu Apr  9 2009
#

PKGVERSION=	1.0
DISTNAME= 	worldModelGrid3DG-genom-${PKGVERSION}
PKGNAME=	worldmodelgrid3dg-genom-${PKGVERSION}
CATEGORIES=	mapping
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=worldModelGrid3D-genom/}

MAINTAINER=	openrobots@laas.fr
#HOMEPAGE=	
COMMENT=	Probabilistic, 3D occupancy grid building - GenoM component

GENOM_MODULE=	worldModelGrid3DG

include ../../architecture/genom/depend.mk
include ../../mapping/worldmodelgrid3d/depend.mk
include ../../mk/robotpkg.mk
