# robotpkg mathematics
#

COMMENT=	Mathematics

SUBDIR+=	boost-numeric-bindings
SUBDIR+=	boost-numeric-bindings-v1
SUBDIR+=	eigen2
SUBDIR+=	eigen3
SUBDIR+=	gbM
SUBDIR+=	geometric-tools
SUBDIR+=	hpp-pinocchio
SUBDIR+=	hrp2-dynamics
SUBDIR+=	jafar-jmath
SUBDIR+=	jrl-dynamics
SUBDIR+=	jrl-dynamics-urdf
SUBDIR+=	jrl-mathtools
SUBDIR+=	lapack
SUBDIR+=	libccd
SUBDIR+=	liblbfgs
SUBDIR+=	meschach
SUBDIR+=	pinocchio
SUBDIR+=	py-eigenpy
SUBDIR+=	py-pinocchio
SUBDIR+=	ros-angles
SUBDIR+=	ros-eigen-stl-containers
SUBDIR+=	ros-geometry
SUBDIR+=	ros-geometry2
SUBDIR+=	ros-random-numbers
SUBDIR+=	sensFusion-libs
SUBDIR+=	t3d
SUBDIR+=	tvmet

include ../mk/robotpkg.subdir.mk
