# robotpkg hardware drivers and low-level software
#

COMMENT=	Hardware drivers and low-level software

SUBDIR+=	GPSNovatel
SUBDIR+=	gyroKVH1000
SUBDIR+=	gyroKVH5000
SUBDIR+=	platine-genom
SUBDIR+=	serial
SUBDIR+=	sickLib
SUBDIR+=	sick-genom

include ../mk/robotpkg.subdir.mk
