# robotpkg localization software
#

COMMENT=	Position estimation and localization

SUBDIR+=	gyro-genom
SUBDIR+=	hueblob-genom
SUBDIR+=	insitu
SUBDIR+=	libpom
SUBDIR+=	pom-genom

include ../mk/robotpkg.subdir.mk
