# robotpkg localization software
#

COMMENT=	Position estimation and localization

SUBDIR+=	GPS-genom
SUBDIR+=	MTI-genom
SUBDIR+=	imu-genom
SUBDIR+=	gyro-genom
SUBDIR+=	hueblob-genom
SUBDIR+=	insitu
SUBDIR+=	libpom
SUBDIR+=	mocap-genom
SUBDIR+=	optitrack-genom3
SUBDIR+=	odokit
SUBDIR+=	pom-genom
SUBDIR+=	pom-genom3
SUBDIR+=	ros-robot-state-publisher
SUBDIR+=	segloc-genom

include ../mk/robotpkg.subdir.mk
