# robotpkg Makefile for:	meta-pkgs/hpp
# Created:			Thomas Moulard on Wed, 8 Sep 2010
#

DISTNAME=	hpp-20180711

COMMENT=	Meta-package for the Humanoid Path Planner
CATEGORIES=	meta-pkgs
MAINTAINER=	hpp@laas.fr

META_PACKAGE=	yes

include ../../path/hpp-core/depend.mk
include ../../path/hpp-util/depend.mk
include ../../path/hpp-corbaserver/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
