# robotpkg Makefile for:	interfaces/ros-map-msgs
# Created:			Anthony Mallet on Mon, 27 Oct 2014
#

ROS_PKG=	map_msgs
ROS_VERSION=	0.0.2
ROS_REPO=	ethz-asl

CATEGORIES=	interfaces
ROS_COMMENT=	messages commonly used in mapping packages

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../lang/ros-message-runtime/depend.mk
include ../../mk/robotpkg.mk
