# robotpkg Makefile for:	devel/ros2-python-cmake-module
# Created:			Anthony Mallet on Mon, 11 Apr 2022
#

ROS2_PKG=	python_cmake_module
ROS2_VERSION=	0.10.0

CATEGORIES=	devel
ROS2_COMMENT=	CMake module for finding Python

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../mk/robotpkg.mk
