# optimization tools
#

COMMENT=	Optimization tools

SUBDIR+=	acado
SUBDIR+=	ipopt
SUBDIR+=	py-crocoddyl
SUBDIR+=	qpoases
SUBDIR+=	roboptim-core
SUBDIR+=	roboptim-core-ipopt-plugin
SUBDIR+=	roboptim-trajectory
SUBDIR+=	tsid

include ../mk/robotpkg.subdir.mk
