# optimization tools
#

COMMENT=	Optimization tools

SUBDIR+=					\
		ipopt				\
		roboptim-core-cfsqp-plugin	\
		roboptim-core-ipopt-plugin	\
		roboptim-trajectory		\
		roboptim-core

include ../mk/robotpkg.subdir.mk
