# robotpkg Makefile for:	middleware/ros-comm
# Created:			Anthony Mallet on Tue,  9 Oct 2012
#

ROS_PKG=		rqt_common_plugins
ROS_VERSION=		0.4.8
ROS_REPO=		ros-visualization

CATEGORIES=		graphics
ROS_COMMENT=		backend graphical tools suite

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../sysutils/ros-rqt-graph/depend.mk
include ../../sysutils/ros-rqt-plot/depend.mk
include ../../mk/robotpkg.mk
