# robotpkg Makefile for:	middleware/ros-genmsg
# Created:			Anthony Mallet on Mon, 10 Dec 2012
#

ROS_PKG=		genmsg
ROS_VERSION=		0.3.10

CATEGORIES=		middleware
ROS_COMMENT=		code generator for ROS .msg format
HOMEPAGE=		http://www.ros.org/wiki/genmsg

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/catkin/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
