# $LAAS: Makefile 2008/10/02 12:15:21 mallet $
#
# Copyright (c) 2008 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      Anthony Mallet on Thu Oct  2 2008
#

DISTNAME=	tvmet-1.7.2
EXTRACT_SUFX=	.tar.bz2

CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=tvmet/}

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://tvmet.sourceforge.net/index.html
COMMENT=	Tiny Vector and Matrix Template library.

GNU_CONFIGURE=	yes

include ../../mk/robotpkg.mk
