# robotpkg Makefile for:	sysutils/ros-console
# Created:			Anthony Mallet on Tue,  4 Sep 2018
#

ROS_PKG=	rosconsole
ROS_VERSION=	1.13.7
PKGNAME=	ros-console-${ROS_VERSION}

CATEGORIES=	sysutils
ROS_COMMENT=	console output library

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/boost-headers/depend.mk
include ../../devel/boost-libs/depend.mk
include ../../devel/log4cxx/depend.mk
include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-ros/depend.mk
include ../../devel/ros-roscpp-core/depend.mk
include ../../mk/sysdep/apr.mk
include ../../mk/robotpkg.mk
