# robotpkg tools documentations
#

COMMENT=	Tool documentations, tutorials and other reference manuals

SUBDIR+=	boost-docs
SUBDIR+=	demo-genom
SUBDIR+=	hpp-doc
SUBDIR+=	hpp-tutorial
SUBDIR+=	robotpkg

include ../mk/robotpkg.subdir.mk
