# robotpkg Makefile for:	robots/rflexclients
# Created:			Arnaud Degroote on Mon, 19 May 2008
#

DISTNAME=		rflexclients-${VERSION}
VERSION=		1.0.1
CATEGORIES=		robots
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git git://git.openrobots.org/robots/rFlex-clients.git

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Driver and interface for Rflex
LICENSE=		isc

GNU_CONFIGURE=		yes

include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../devel/mkdep/depend.mk
include ../../mk/robotpkg.mk
