# robotpkg Makefile for:	devel/hpp-kwsio
# Created:			Anthony Mallet on Fri, 13 Jul 2007
#

HPP_PACKAGE=		hpp-kwsio
HPP_VERSION=		1.2
PKGREVISION=
MASTER_REPOSITORY=	git git@github.com:laas/hpp-kwsio

CATEGORIES=		devel
HPP_COMMENT=		Input and Output functions for KineoWorks(tm) package.
LICENSE=		gnu-lgpl-v2

HPP_BUILD_SYSTEM=	cmake

include ../../meta-pkgs/hpp/Makefile.common

include ../../pkgtools/pkg-config/depend.mk
include ../../mk/sysdep/doxygen.mk
include ../../mk/sysdep/graphviz.mk
include ../../mk/sysdep/kineoworks.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
