# $NetBSD$
#

DISTNAME=		genPos-genom-0.1
CATEGORIES=		architecture
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Base Position  module for GenoM 

GNU_CONFIGURE=		yes
USE_PKG_CONFIG=		yes

GENOM_MODULE=		genPos
include ../../architecture/genom/depend.mk

include ../../mk/robotpkg.mk
