# robotpkg supervision tools
#

COMMENT=	Supervision tools

SUBDIR+=	matlab-genomix
SUBDIR+=	openprs
SUBDIR+=	ros-executive-smach
SUBDIR+=	transgen
SUBDIR+=	transgen3

include ../mk/robotpkg.subdir.mk
