# robotpkg sysdep/cmake.mk
# Created:			Anthony Mallet on Thu Jan 22 2009
#

DEPEND_DEPTH:=		${DEPEND_DEPTH}+
CMAKE_DEPEND_MK:=	${CMAKE_DEPEND_MK}+

ifeq (+,$(DEPEND_DEPTH))
DEPEND_PKG+=		cmake
endif

ifeq (+,$(CMAKE_DEPEND_MK)) # ----------------------------------------------

PREFER.cmake?=		system

DEPEND_USE+=		cmake
DEPEND_ABI.cmake?=	cmake>=2.6
DEPEND_METHOD.cmake+=	build
SYSTEM_SEARCH.cmake=	'bin/cmake:s/[^-.0-9]//g;y/-/./;p:% --version'

USE_CMAKE?=		yes
export CMAKE=		${PREFIX.cmake}/bin/cmake


# Define the proper cmake environment so that find_package() looks up the
# package in the right path
#
CONFIGURE_ENV+=\
  $(foreach 1,${DEPEND_USE},$(foreach 2,${SYSTEM_FILES.$1},$(strip	\
    $(if $(filter Find%.cmake,$(notdir $2)),				\
      $(patsubst Find%.cmake,%,$(notdir $2))_DIR=$(dir $2))		\
    $(if $(filter %-config.cmake,$(notdir $2)),				\
      $(patsubst %-config.cmake,%,$(notdir $2))_DIR=$(dir $2)))))


# Use the install_manifest.txt file generated by cmake install for the
# print-PLIST target, because cmake doesn't change the date of installed
# files.
#
PRINT_PLIST_FILES_CMD+=\
	${CAT} 2>/dev/null $(or						\
	  $(wildcard $(addsuffix /install_manifest.txt,${BUILD_DIRS})),	\
	  $(wildcard $(addprefix ${WRKSRC}/,				\
	    $(addsuffix /install_manifest.txt,${BUILD_DIRS}))),		\
	  /dev/null);

endif # CMAKE_DEPEND_MK ----------------------------------------------------

DEPEND_DEPTH:=		${DEPEND_DEPTH:+=}
