# robotpkg Makefile for:	devel/orocos-logcpp
# Created:			Arnaud Degroote on Wed, 21 Aug 2013
#

OROCOS_PKG=		log4cpp
CATEGORIES=		devel

include ../../meta-pkgs/orocos-toolchain/Makefile.common

COMMENT=		C++ logging library with real-time support

include ../../mk/sysdep/cmake.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
