# robotpkg Makefile for:	devel/hpp-model
# Created:			Anthony Mallet on Mon, 18 Feb 2008
#

HPP_PACKAGE=		hpp-model
HPP_VERSION=		2.1
MASTER_REPOSITORY=	${MASTER_REPOSITORY_JRL}/algo/hpp-model

CATEGORIES=	devel
HPP_COMMENT=	robots, joints and bodies with dynamics properties
LICENSE=	cnrs-hpp-closed-source

HPP_BUILD_SYSTEM=	cmake
include ../../meta-pkgs/hpp/Makefile.common

include ../../devel/hpp-kwsio/depend.mk
include ../../devel/hpp-util/depend.mk
include ../../math/jrl-dynamics/depend.mk
include ../../path/kineo-pp/depend.mk
include ../../mk/robotpkg.mk
