# robotpkg Makefile for:	math/hpp-pinocchio
# Created:			Guilhem Saurel on Wed, 14 Mar 2018
#

HPP_PACKAGE=	hpp-pinocchio
HPP_VERSION=	4.10.1
PKGREVISION=	1

CATEGORIES=	math
HPP_COMMENT=	Wrapping of the kinematic/dynamic chain Pinocchio for HPP.

include ../../meta-pkgs/hpp/Makefile.common

# TODO: for tests
#include ../../wip/py-hpp-baxter/depend.mk
#include ../../robots/romeo-description/depend.mk

include ../../mapping/octomap/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/pinocchio/depend.mk
include ../../path/hpp-fcl/depend.mk
include ../../path/hpp-util/depend.mk
include ../../graphics/assimp/depend.mk
include ../../simulation/hpp-environments/depend.mk
include ../../robots/example-robot-data/depend.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
