# robotpkg simulation tools
#

COMMENT=	Simulation tools

SUBDIR+=	gazebo-ros-pkgs
SUBDIR+=	hpp-environments
SUBDIR+=	libmrsim
SUBDIR+=	morse
SUBDIR+=	morse-yarp
SUBDIR+=	mrsim-gazebo
SUBDIR+=	mrsim-genom3
SUBDIR+=	openhrp3
SUBDIR+=	optitrack-gazebo
SUBDIR+=	py-hpp-environments

include ../mk/robotpkg.subdir.mk
