# robotpkg Makefile for:	graphics/ros-convex-decomposition
# Created:			Séverin Lemaignan on Tue, 06 Aug 2013
#

ROS_PKG=	convex_decomposition
ROS_VERSION=	0.1.12

CATEGORIES=	graphics
ROS_COMMENT=	convex mesh generation library

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../mk/robotpkg.mk
