# robotpkg Makefile for:	path/hpp-core
# Created:			Anthony Mallet on Fri, 13 Jul 2007
#

HPP_PACKAGE=		hpp-core
HPP_VERSION=		2.5.1
PKGREVISION=
MASTER_REPOSITORY=	git git@github.com:laas/hpp-core

CATEGORIES=	path
HPP_COMMENT=	interface with KineoWorks(tm)
LICENSE=	cnrs-hpp-closed-source

HPP_BUILD_SYSTEM=	cmake
include ../../meta-pkgs/hpp/Makefile.common

include ../../devel/hpp-model/depend.mk
include ../../devel/hpp-util/depend.mk
include ../../devel/hpp-kwsplus/depend.mk
include ../../mk/robotpkg.mk
