# $NetBSD$
#

DISTNAME=	hppcore-${VERSION}
PKGNAME=	hpp-core-${VERSION}
VERSION=	1.0

CATEGORIES=	path
MASTER_SITES=	${MASTER_SITE_OPENROBOTS}

MAINTAINER=	gepetto@laas.fr
#HOMEPAGE=	
COMMENT=	Basic classes used as interfaces with KineoWorks(tm).

DEPENDS+=	hpp-kwsplus>=1.0:../../devel/hpp-kwsplus

GNU_CONFIGURE=	yes
USE_PKG_CONFIG=	yes

include ../../mk/robotpkg.mk
