# robotpkg Makefile for:	path/hpp-tutorial
# Created:			Florent Lamiraux on Thu, 12 Mar 2015
#

HPP_PACKAGE=		hpp_tutorial

CATEGORIES=		doc
HPP_COMMENT=		Tutorial for manipulation and path planning

USE_PYTHON=		true

include ../../meta-pkgs/hpp/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../mapping/octomap/depend.mk
include ../../optimization/roboptim-trajectory/depend.mk
include ../../graphics/hpp-gepetto-viewer/depend.mk
include ../../path/py-hpp-corbaserver/depend.mk
include ../../path/hpp-util/depend.mk
include ../../path/py-hpp-manipulation-corba/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
