# $Id:$
#

DISTNAME=	hpppython-${VERSION}
PKGNAME=	hpppython-${VERSION}
VERSION=	1.0

CATEGORIES=	scripts
MASTER_SITES=	${MASTER_SITE_OPENROBOTS}

MAINTAINER=	gepetto@laas.fr
#HOMEPAGE=	
COMMENT=	Python scripts creating CORBA client of hppCorbaServer

GNU_CONFIGURE=	yes
USE_PKG_CONFIG=	yes

include ../../devel/omniORBpy/depend.mk
include ../../mk/robotpkg.mk
