# $NetBSD$
#

DISTNAME=	hpppython-${VERSION}
PKGNAME=	hpppython-${VERSION}
VERSION=	1.0

CATEGORIES=	scripts
MASTER_SITES=	${MASTER_SITE_OPENROBOTS}

MAINTAINER=	gepetto@laas.fr
#HOMEPAGE=	
COMMENT=	Python scripts creating CORBA client of hppCorbaServer

DEPENDS+=       omniORB>=4.1.0:../../devel/omniORB

GNU_CONFIGURE=	yes
USE_PKG_CONFIG=	yes

include ../../mk/robotpkg.mk
