# robotpkg Makefile for:	interfaces/ros2-rosidl-defaults
# Created:			Anthony Mallet on Tue, 5 Apr 2022
#

ROS2_PKG=	rosidl_defaults
ROS2_VERSION=	1.6.0

CATEGORIES=	interfaces
ROS2_COMMENT=	default rosidl runtime and generators.

ROS2_SUBPKGS=\
  rosidl_default_generators	\
  rosidl_default_runtime

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../interfaces/ros2-rosidl-core/depend.mk
include ../../mk/robotpkg.mk
