# robotpkg Makefile for:	robots/py39-solo-rbprm
# Created:			Guilhem Saurel on Tue,  1 Jun 2021
#

HPP_PACKAGE=			solo-rbprm
HPP_COMMENT=			Database for solo robot using hpp-rbprm

CATEGORIES=			robots

USE_PYTHON=			true

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
