#
# Copyright (c) 2010 LAAS/CNRS
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without   fee is hereby granted, provided   that the above  copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS  SOFTWARE INCLUDING ALL  IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR  BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR  ANY DAMAGES WHATSOEVER RESULTING  FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION,   ARISING OUT OF OR IN    CONNECTION WITH THE USE   OR
# PERFORMANCE OF THIS SOFTWARE.
#
#                                            Anthony Mallet on Wed Mar 24 2010
#

DISTNAME=	purple-ball-1.0

CATEGORIES=		scripts
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=purple-ball/}
MASTER_REPOSITORY=	git ssh://softs.laas.fr/git/robots/purple-ball

MAINTAINER=	openrobots@laas.fr
#HOMEPAGE=
COMMENT=	Supervision scripts for the HRP-2 "purple-ball" demonstration

USE_LANGUAGES=	# empty

GNU_CONFIGURE=	yes

include ../../robots/hrp2-genom/depend.mk
include ../../audio/speett-genom/depend.mk
include ../../audio/textos-genom/depend.mk
include ../../image/viam-genom/depend.mk
include ../../image/stereopixel-genom/depend.mk
include ../../localization/hueblob-genom/depend.mk
include ../../path/gik-genom/depend.mk
include ../../path/walk-genom/depend.mk
include ../../mk/sysdep/tcl.mk
include ../../mk/sysdep/tk.mk
include ../../mk/robotpkg.mk

