# robotpkg knowledge representation packages
#

COMMENT=	Knowledge representation tools

SUBDIR+=	jena
SUBDIR+=	pellet
SUBDIR+=	liboro
SUBDIR+=	oro-server
SUBDIR+=	py-oro

include ../mk/robotpkg.subdir.mk
