# robotpkg Makefile for:	hardware/gyroKVH5000
# Created:			Arnaud Degroote on Mon, 14 Jul 2008
#

DISTNAME=		gyro-libs-2.0
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/gyro-libs

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Driver and interface for KVH FOG gyros

LICENSE=		isc

GNU_CONFIGURE=		yes

include ../../middleware/pocolibs/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
