# $Id: Makefile 2007/07/11 14:36:51 mallet $
#

DISTNAME=		picoweb-1.0
CATEGORIES=		www
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		https://softs.laas.fr/openrobots/
COMMENT=		Dedicated HTTP server for GenoM modules.


GNU_CONFIGURE=		yes
DEPENDS+=		mkdep>=2.6:../../devel/mkdep

include ../../devel/pocolibs/depend.mk
include ../../mk/robotpkg.mk
