# $LAAS: Makefile 2008/12/10 23:29:12 tho $
#
# Copyright (c) 2008 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      Anthony Mallet on Wed Dec 10 2008
#

include ../../lang/gcc42/Makefile.common

DISTNAME=	gcc4-fortran-${GCC_VERSION}
META_PACKAGE=	yes

include ../../lang/gcc42-fortran/depend.mk
include ../../mk/robotpkg.mk
