# robotpkg Makefile for:	math/ros-geometry
# Created:			Séverin Lemaignan on Mon, 5 Aug 2013
#

ROS_PKG=	geometry
ROS_VERSION=	1.9.30
ROS_METAPKG=	yes

CATEGORIES=	math localization
ROS_COMMENT=	geometry library (including TF frame management)

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../interfaces/ros-std-msgs/depend.mk
include ../../lang/ros-message-generation/depend.mk
include ../../math/eigen3/depend.mk
include ../../math/ros-angles/depend.mk
include ../../middleware/ros-actionlib/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../motion/ros-orocos-kdl/depend.mk
include ../../mk/robotpkg.mk
