# robotpkg Makefile for:	interfaces/openrobots-idl
# Created:			Anthony Mallet on Mon,  9 Nov 2015
#

DISTNAME=		openrobots-idl-1.4
CATEGORIES=		interfaces
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=${PKGBASE}/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}openrobots-idl

MAINTAINER=		openrobots@laas.fr
COMMENT=		Common IDL interfaces for genom3 components
LICENSE=		isc

GNU_CONFIGURE=		yes

include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
