# robotpkg programming languages
#

COMMENT=	Programming languages

SUBDIR+=	jython
SUBDIR+=	python31
SUBDIR+=	python32
SUBDIR+=	ros-gencpp
SUBDIR+=	ros-genlisp
SUBDIR+=	ros-genpy
SUBDIR+=	ros-langs-dev
SUBDIR+=	ros-message-generation
SUBDIR+=	sun-jdk

include ../mk/robotpkg.subdir.mk
