# robotpkg Makefile for:	meta-pkgs/ros-robot
# Created:			Séverin Lemaignan on Tue, 06 Aug 2013
#

DISTNAME=	ros-robot-1.4.1
CATEGORIES=	meta-pkgs
META_PACKAGE=	yes

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://www.ros.org/wiki/
COMMENT=	The Robotic Operating System - robot variant

PREFER.ros?=	robotpkg
DEPEND_ABI.ros=	ros==melodic

include ../../devel/ros-bond-core/depend.mk
include ../../devel/ros-filters/depend.mk
include ../../devel/ros-nodelet-core/depend.mk
include ../../devel/ros-ros/depend.mk
include ../../devel/ros-xacro/depend.mk
include ../../graphics/ros-kdl-parser/depend.mk
include ../../graphics/ros-urdf/depend.mk
include ../../interfaces/ros-control-msgs/depend.mk
include ../../localization/ros-joint-state-publisher/depend.mk
include ../../localization/ros-robot-state-publisher/depend.mk
include ../../math/ros-geometry/depend.mk
include ../../middleware/ros-actionlib/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../middleware/ros-dynamic-reconfigure/depend.mk
include ../../supervision/ros-executive-smach/depend.mk
include ../../sysutils/ros-diagnostics/depend.mk
include ../../mk/robotpkg.mk
