# robotpkg robots specific packages
#

COMMENT=	Robots specific packages

SUBDIR+=	hrp2-10
SUBDIR+=	hrp2-14
SUBDIR+=	hrpsys-base
SUBDIR+=	ivmob-genom
SUBDIR+=	ivmob-libs
SUBDIR+=	jloco-genom
SUBDIR+=	mana-emergency
SUBDIR+=	mikrokopter-genom3
SUBDIR+=	mor-libs
SUBDIR+=	nao-robot
SUBDIR+=	neobotix-libs
SUBDIR+=	play-genom
SUBDIR+=	player20-libs
SUBDIR+=	rflex-genom
SUBDIR+=	rflexclients
SUBDIR+=	rmp-libs
SUBDIR+=	rmp400-genom
SUBDIR+=	rmp440-genom
SUBDIR+=	rmp440-genom3
SUBDIR+=	rmp440-libs
SUBDIR+=	romeo-description
SUBDIR+=	scout-genom
SUBDIR+=	tk3-matlab
SUBDIR+=	tk3-mikrokopter

include ../mk/robotpkg.subdir.mk
