# robotpkg robots specific packages
#

COMMENT=	Robots specific packages

SUBDIR+=	hrp2-14
SUBDIR+=	hrp2-genom
SUBDIR+=	mapkit
SUBDIR+=	odokit
SUBDIR+=	platine-genom
SUBDIR+=	rflex-genom
SUBDIR+=	rflexclients
SUBDIR+=	segkit
SUBDIR+=	sick-genom

include ../mk/robotpkg.subdir.mk
