# robotpkg abstract programming interfaces
#

COMMENT=	Abstract programming interfaces

SUBDIR+=	genBasic-genom
SUBDIR+=	genHum-genom
SUBDIR+=	genPos-genom
SUBDIR+=	abstract-robot-dynamics
SUBDIR+=	abstract-gik-task
SUBDIR+=	humanoid-nav-msgs
SUBDIR+=	jrl-mal
SUBDIR+=	openrobots-idl
SUBDIR+=	openrobots2-idl
SUBDIR+=	ros-comm-msgs
SUBDIR+=	ros-common-msgs
SUBDIR+=	ros-control-msgs
SUBDIR+=	ros-navigation-msgs
SUBDIR+=	ros-std-msgs
SUBDIR+=	ros2-rosidl
SUBDIR+=	ros2-rosidl-python
SUBDIR+=	ros2-rosidl-typesupport

include ../mk/robotpkg.subdir.mk
