# robotpkg Makefile for:	interfaces/ros2-rosidl-dynamic-typesupport
# Created:			Anthony Mallet on Thu,  7 Sep 2023
#

ROS2_PKG=	rosidl_dynamic_typesupport
ROS2_VERSION=	0.1.1

CATEGORIES=	interfaces
ROS2_COMMENT=	runtime typesupport and serialization

include ../../meta-pkgs/ros2-core/Makefile.common

include ../../devel/ament-cmake-ros/depend.mk
include ../../devel/ros2-rcutils/depend.mk
include ../../interfaces/ros2-rosidl/depend.mk
include ../../mk/robotpkg.mk
