# robotpkg Makefile for:	robots/py39-simple-humanoid-rbprm
# Created:			Guilhem Saurel on Wed, 14 Apr 2021
#

HPP_PACKAGE=	simple-humanoid-rbprm
HPP_COMMENT=	Database for simple-humanoid robot using hpp-rbprm

CATEGORIES=	robots

USE_PYTHON=	true

include ../../meta-pkgs/hpp/Makefile.common

include ../../robots/example-robot-data/depend.mk

include ../../mk/sysdep/python.mk
include ../../mk/language/c.mk
include ../../mk/language/c++.mk
include ../../mk/robotpkg.mk
