# robotpkg software development tools
#

COMMENT=	Software development tools

SUBDIR+=	cortex-sdk
SUBDIR+=	boost-build
SUBDIR+=	boost-headers
SUBDIR+=	boost-jam
SUBDIR+=	boost-libs
SUBDIR+=	boost-log
SUBDIR+=	gbx-share
SUBDIR+=	gbx-flexiport
SUBDIR+=	jafar-kernel
SUBDIR+=	jrl-modelloader
SUBDIR+=	jsoncpp
SUBDIR+=	libedit
SUBDIR+=	log4cxx
SUBDIR+=	mkdep
SUBDIR+=	orocos-log4cpp
SUBDIR+=	py-simpleparse
SUBDIR+=	ros-bond-core
SUBDIR+=	ros-catkin
SUBDIR+=	ros-class-loader
SUBDIR+=	ros-filters
SUBDIR+=	ros-nodelet-core
SUBDIR+=	ros-pluginlib
SUBDIR+=	ros-ros
SUBDIR+=	ros-roscpp-core
SUBDIR+=	ros-xacro
SUBDIR+=	swig
SUBDIR+=	yaml-cpp

include ../mk/robotpkg.subdir.mk
