# robotpkg software development tools
#

COMMENT=	Software development tools

SUBDIR+=	boost
SUBDIR+=	boost-build
SUBDIR+=	boost-docs
SUBDIR+=	boost-headers
SUBDIR+=	boost-jam
SUBDIR+=	boost-numeric-bindings
SUBDIR+=	evart-sdk
SUBDIR+=	hpp-corbaserver
SUBDIR+=	hpp-kwsio
SUBDIR+=	hpp-kwsplus
SUBDIR+=	hpp-model
SUBDIR+=	jrl-modelloader
SUBDIR+=	libedit
SUBDIR+=	mkdep
SUBDIR+=	omniORB
SUBDIR+=	omniORBpy
SUBDIR+=	pocolibs
SUBDIR+=	sun-java3d
SUBDIR+=	sun-jmf

include ../mk/robotpkg.subdir.mk
