# robotpkg tools for use in the packages collection
#

COMMENT=	Tools for use in the packages collection

SUBDIR+=	digest
SUBDIR+=	install-sh
SUBDIR+=	libnbcompat
SUBDIR+=	libtool
SUBDIR+=	pax
SUBDIR+=	pkg-config
SUBDIR+=	pkg_install
SUBDIR+=	rbulkit
SUBDIR+=	robotpkg_chk
SUBDIR+=	robotpkgdb
SUBDIR+=	tnftp
SUBDIR+=	url2robotpkg

include ../mk/robotpkg.subdir.mk
