# robotpkg Makefile for:	sysutils/tk3-flash
# Created:			Anthony Mallet on Tue, 27 Jan 2015
#

DISTNAME=		tk3-flash-1.1
CATEGORIES=		sysutils
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=tk3-flash/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}tk3-flash

COMMENT=	Programming utility for Mikrokopter hardware
HOMEPAGE=	http://git.openrobots.org/projects/tk3-flash
LICENSE=	2-clause-bsd
MAINTAINER=	openrobots@laas.fr

GNU_CONFIGURE=	yes

include ../../mk/sysdep/libelf.mk
include ../../mk/language/c.mk
include ../../mk/robotpkg.mk
