# robotpkg Makefile for:	math/ros-angles
# Created:			Anthony Mallet on Thu,  4 Jul 2013
#

ROS_PKG=	angles
ROS_METAPKG=	yes
ROS_VERSION=	1.9.9
ROS_REPO=	ros

CATEGORIES=	math
ROS_COMMENT=	simple math utilities to work with angles


include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../mk/robotpkg.mk
