# robotpkg Makefile for:	lang/ros-langs
# Created:			Anthony Mallet on Mon, 10 Dec 2012
#

ROS_PKG=		langs
ROS_VERSION=		0.3.5

CATEGORIES=		lang
ROS_COMMENT=		meta package for language bindings of messages
HOMEPAGE=		http://www.ros.org

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/catkin/depend.mk
include ../../devel/roscpp-core/depend.mk
include ../../lang/ros-langs-dev/depend.mk
include ../../mk/robotpkg.mk
