# robotpkg sysutils
#

COMMENT=	Sysutils

SUBDIR+=	alog
SUBDIR+=	ament-index
SUBDIR+=	arduio
SUBDIR+=	arduio-genom3
SUBDIR+=	console-bridge
SUBDIR+=	hrp2-bringup
SUBDIR+=	hrp2-computer-monitor
SUBDIR+=	interceptty
SUBDIR+=	py-aafigure
SUBDIR+=	py-ament-package
SUBDIR+=	py-catkin-pkg
SUBDIR+=	py-rosdep
SUBDIR+=	py-rosdistro
SUBDIR+=	py-rospkg
SUBDIR+=	py-ros2-rpyutils
SUBDIR+=	ros-console
SUBDIR+=	ros-console-bridge
SUBDIR+=	ros-diagnostics
SUBDIR+=	ros-rospack
SUBDIR+=	ros-rqt-graph
SUBDIR+=	ros-rqt-plot
SUBDIR+=	ros-rviz
SUBDIR+=	ros2-environment
SUBDIR+=	ros2-ros-workspace
SUBDIR+=	ros2-tracing
SUBDIR+=	tk3-flash
SUBDIR+=	tth
SUBDIR+=	y2l

include ../mk/robotpkg.subdir.mk
