# robotpkg sysutils
#

COMMENT=	Sysutils

SUBDIR+=	alog
SUBDIR+=	py-aafigure
SUBDIR+=	py-catkin-pkg
SUBDIR+=	py-rosdep
SUBDIR+=	py-rosdistro
SUBDIR+=	py-rospkg
SUBDIR+=	ros-rospack
SUBDIR+=	tth
SUBDIR+=	y2l

include ../mk/robotpkg.subdir.mk
