# robotpkg networking tools
#

COMMENT=        Networking tools

SUBDIR+=        evart-client
SUBDIR+=        evart-stream
SUBDIR+=	libfetch
SUBDIR+=	libtclserv_client
SUBDIR+=	netshring
SUBDIR+=	tclpcap
SUBDIR+=	zeromq

include ../mk/robotpkg.subdir.mk
