# robotpkg networking tools
#

COMMENT=        Networking tools

SUBDIR+=        evart-client
SUBDIR+=        evart-stream
SUBDIR+=        genomix
SUBDIR+=	libfetch
SUBDIR+=	libtclserv_client
SUBDIR+=	netshring
SUBDIR+=	py-poco
SUBDIR+=	ros-resource-retriever
SUBDIR+=	rosix
SUBDIR+=	tclpcap
SUBDIR+=	tclserv

include ../mk/robotpkg.subdir.mk
