# robotpkg image processing utilities
#

COMMENT=	Image processing utlities

SUBDIR+=	libdc1394-1
SUBDIR+=	libdc1394
SUBDIR+=	libimages3d
SUBDIR+=	libraw1394
SUBDIR+=	libstereopixel
SUBDIR+=	opencv
SUBDIR+=	viam-libs
SUBDIR+=	viam-genom

include ../mk/robotpkg.subdir.mk
