# robotpkg image processing utilities
#

COMMENT=	Image processing utlities

SUBDIR+=	artoolkitplus
SUBDIR+=	coriander
SUBDIR+=	libdc1394-1
SUBDIR+=	libdc1394
SUBDIR+=	libimages3d
SUBDIR+=	libraw1394
SUBDIR+=	libstereopixel
SUBDIR+=	opencv1
SUBDIR+=	opencv
SUBDIR+=	openni-nite
SUBDIR+=	sift
SUBDIR+=	stereopixel-genom
SUBDIR+=	viam-libs
SUBDIR+=	viam-genom
SUBDIR+=	viman-genom
SUBDIR+=	visp

include ../mk/robotpkg.subdir.mk
